/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilegra0225' at '09/05/17 13:48' with Gradle 2.14.1
 *
 * @author ilegra0225, @date 09/05/17 13:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
